### ISSUE TITLE
URL repeterer

### ISSUE THREAD

**Issue by olejorgenbakken** [navikt/mangfold-i-mai#35]
URLen repeterer seg selv? Hva er grunnen til det? Eksempelvis: https://mangfoldimai.no/mangfold-i-mai/

**Comment by MikAoJk** [comment]
Antar at det er pga denne: https://github.com/navikt/mangfold-i-mai/blob/b1f47c9cb6067e46929293f87f6ba30655c3c3ec/_config.yml#L25

**Comment by olejorgenbakken** [comment]
Det var det jeg tenkte! Er det noen fornuftig måte å endre så mangfoldimai.no er rot, eller vil det skape massssse krøll?

**Comment by MikAoJk** [comment]
Tror det er ein del linker som er delt her og der.
Så eg tipper dessvere det blir litt krøll viss men endrer på denne nå :crying_cat_face:

**Comment by sarahbrodwall** [comment]
Det har å gjøre med måten Github Pages funker.  Når man bruker Github Pages til hosting, ser URLene sånn ut: https://navikt.github.io/mangfold-i-mai/  Tipper det hadde gått an å finne en vei rundt dette, men vi har hatt lite tid og kapasitet og styrer ikke DNS-rekordene selv, så det har ikke vært en prioritet.  

Anbefaler at vi fikser denne om vi gjør denne neste år.  Da kan vi også undersøke andre hostingmuligheter i tillegg og får litt større frihet.
