### ISSUE TITLE
Fix cron job

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/mangfold-i-mai#45]
Jeg vil bare at den bygger på nytt tidlig hver dag for å refreshe forsiden.
![image](https://user-images.githubusercontent.com/91880567/165898697-1716ac4f-ce95-4d92-8403-5853c41238db.png)

https://github.com/navikt/mangfold-i-mai/actions/runs/2242870135

**Comment by olejorgenbakken** [comment]
Jeg kan veldig lite om github actions, men [er dette en mulig løsning](https://svrooij.io/2020/06/27/rebuild-github-pages/)?

**Comment by sarahbrodwall** [comment]
lool det er oppskriften jeg brukte!  Secret'en og alt er på plass, du kan gjerne utforske videre, eller kanskje @lillebo kan bistå?

Det ligger forresten en liten kommentar helt nederst i HTMLen som sier når siste builden kjørte.

**Comment by sarahbrodwall** [comment]
@KenAJoh @larseirikhansen Noe clue om hva jeg kan gjøre her?  Jobben kjører, men jeg får "not found": https://github.com/navikt/mangfold-i-mai/runs/6385080613?check_suite_focus=true

**Comment by KenAJoh** [comment]
Ser ut som det fungerer nå, så antar det ble fikset 🐛
