### ISSUE TITLE
Ordne opp i responsivitet

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/mangfold-i-mai#9]
Særlig fontstørrelsene.

**Comment by Lillebo** [comment]
Hva bør fikses her? 🤔 Syns den ser fin ut på mobil jeg

**Comment by sarahbrodwall** [comment]
Aah, ser bedre ut i Chrome enn i Brave. :) Tror jeg skal lukke denne, da.

**Comment by Lillebo** [comment]
Helt fin i Firefox også 🙂👍
